# 5. Numerical Python mit NumPy 

In [2]:
import numpy as np

## 5.1 NumPy Arrays Grundlagen

In [3]:
a = [1,2,3,4,5,6,7,8,9]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
b = np.array(a)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np?

Type:        module
String form: <module 'numpy' from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py'>
File:        /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets 

In [6]:
b[3] = 2.71

In [7]:
b

array([1, 2, 3, 2, 5, 6, 7, 8, 9])

In [8]:
b?

Type:        ndarray
String form: [1 2 3 2 5 6 7 8 9]
Length:      9
File:        /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dt

In [9]:
c = np.array([2,3,4,3.1415,1])

In [10]:
c

array([2.    , 3.    , 4.    , 3.1415, 1.    ])

In [11]:
c.sort()
c

array([1.    , 2.    , 3.    , 3.1415, 4.    ])

In [12]:
d = np.array([*range(100)])
d.shape

(100,)

In [13]:
t = (100,)

In [14]:
type(t)

tuple

In [15]:
d.shape

(100,)

In [16]:
d.reshape(5,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [17]:
d= d.reshape(2,5,10)
d

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [18]:
d[1][0]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [19]:
d=d.reshape(100,)

In [20]:
np.zeros(10, dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [21]:
np.ones(10, dtype=str)

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [22]:
np.full((4,7),4711)

array([[4711, 4711, 4711, 4711, 4711, 4711, 4711],
       [4711, 4711, 4711, 4711, 4711, 4711, 4711],
       [4711, 4711, 4711, 4711, 4711, 4711, 4711],
       [4711, 4711, 4711, 4711, 4711, 4711, 4711]])

In [23]:
e = np.array([range(index, index+13,3) for index in [9,8,5,4]])

In [24]:
e

array([[ 9, 12, 15, 18, 21],
       [ 8, 11, 14, 17, 20],
       [ 5,  8, 11, 14, 17],
       [ 4,  7, 10, 13, 16]])

In [25]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [26]:
np.arange(5,17,2,dtype=int)

array([ 5,  7,  9, 11, 13, 15])

In [27]:
np.linspace(5,25,10)

array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
       16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ])

In [28]:
np.random.random(19)

array([0.89309693, 0.96825366, 0.21735932, 0.36283509, 0.39315443,
       0.30645004, 0.78403575, 0.46261568, 0.90421361, 0.95917101,
       0.97963057, 0.0655272 , 0.56654111, 0.67439468, 0.6092088 ,
       0.32477259, 0.03921571, 0.20418129, 0.6893675 ])

In [29]:
np.random.random((5,5))

array([[0.01957611, 0.12494186, 0.78073573, 0.01759013, 0.71302742],
       [0.67655098, 0.60266243, 0.57369528, 0.79612125, 0.43475865],
       [0.14674561, 0.67225176, 0.33925428, 0.65126535, 0.52460146],
       [0.77252916, 0.27493092, 0.7055827 , 0.34061902, 0.16371249],
       [0.34638986, 0.38344759, 0.10840159, 0.02564004, 0.76946972]])

In [30]:
mittelwert = -5
standardabweichung = 5
anzahl = 100
np.random.normal(mittelwert, standardabweichung, anzahl)

array([ -3.46899762, -15.76461267,  -8.62746391,  -8.90805013,
        -2.5601885 ,  -3.54426752,  -6.86038501,  -9.70265049,
        -3.34823454,  -4.74204464,  -5.24261052, -13.97177316,
       -13.87518447,  -3.09907909,  -6.63222724,  -1.24933665,
        -0.38014313,  -5.93719017,  -0.03454166, -10.54869653,
        -1.83094266, -14.52389114, -11.3862834 ,  -7.50918498,
        -5.47304366,  -9.20512362,  -8.96901498,  -5.19255442,
       -12.40231724,  -5.332596  ,  -8.19082862,  -0.51591368,
        -6.06464964,  -5.61497119,  11.88369761,   1.07613474,
        -6.69679096,   7.97078437,  -8.46819009,   2.58612092,
        -2.70966157, -13.08568073, -14.07718793,  -1.38712715,
        -3.04783423,  -9.84154293,  -5.04527632,  -9.07324661,
        -2.28650454,  -2.15302166,  -8.39750894,  -2.71674771,
        -2.39427145,  -9.41677865,   1.33634741,  -4.77915411,
        -4.66254464,  -7.74023256, -12.69325968, -14.42342937,
         1.0368458 ,  -3.94920853,  -8.67277831,  -4.97

In [31]:
z = np.random.normal(mittelwert, standardabweichung, (3,5,4))
z[2]

array([[  3.56257049,  -7.09289211,  -5.81469151,  11.71735236],
       [ -3.47440514,  -2.01700792,  -7.84225743,   2.67003477],
       [-12.89241621,  -4.23612986,  -7.18518034,  -5.40402663],
       [ -5.37264516,  -6.46952042, -12.65006832,  -7.2587161 ],
       [  2.25935478,  -5.36601857,   1.51903298,  -0.47190163]])

In [32]:
np.random.seed(42)
von = 10  # inklusive
bis = 100 # exklusive
a1 = np.random.randint(von, bis, 10)
a2 = np.random.randint(von, bis, (2,3))
a3 = np.random.randint(von, bis, (3,4,5))
a4 = np.random.randint(von, bis, (3,2,5,2))
a5 = np.random.randint(von, bis, (4,5,3,2,2))
myArrays = [a1,a2,a3,a4,a5]
a5

array([[[[[14, 99],
          [23, 36]],

         [[18, 88],
          [24, 99]],

         [[51, 86],
          [60, 72]]],


        [[[61, 13],
          [32, 24]],

         [[52, 38],
          [45, 22]],

         [[41, 80],
          [68, 95]]],


        [[[37, 75],
          [51, 54]],

         [[71, 66],
          [15, 37]],

         [[37, 53],
          [93, 39]]],


        [[[71, 84],
          [98, 71]],

         [[10, 36],
          [71, 86]],

         [[12, 79],
          [81, 36]]],


        [[[18, 71],
          [46, 60]],

         [[53, 33],
          [88, 68]],

         [[41, 97],
          [61, 71]]]],



       [[[[67, 61],
          [21, 48]],

         [[11, 12],
          [65, 90]],

         [[68, 11],
          [11, 63]]],


        [[[96, 10],
          [28, 11]],

         [[62, 53],
          [99, 41]],

         [[79, 41],
          [77, 64]]],


        [[[84, 65],
          [26, 47]],

         [[33, 78],
          [79, 95]],

         [[20, 25]

In [33]:
for i in range(len(myArrays)):
    print("a{0:}: Dimension {1:}, Size {2:3d}, Itemsize {3:}, NBytes {4:4d}, Shape {5:}".format(
        i+1,myArrays[i].ndim,
        myArrays[i].size,
        myArrays[i].itemsize,
        myArrays[i].nbytes,
        myArrays[i].shape))

a1: Dimension 1, Size  10, Itemsize 8, NBytes   80, Shape (10,)
a2: Dimension 2, Size   6, Itemsize 8, NBytes   48, Shape (2, 3)
a3: Dimension 3, Size  60, Itemsize 8, NBytes  480, Shape (3, 4, 5)
a4: Dimension 4, Size  60, Itemsize 8, NBytes  480, Shape (3, 2, 5, 2)
a5: Dimension 5, Size 240, Itemsize 8, NBytes 1920, Shape (4, 5, 3, 2, 2)


In [34]:
a1

array([61, 24, 81, 70, 30, 92, 96, 84, 84, 97])

In [35]:
a1[5]

92

In [36]:
a1[5] = -5
a1

array([61, 24, 81, 70, 30, -5, 96, 84, 84, 97])

In [37]:
a1[-1]

97

In [38]:
a1[-4] = -4
a1

array([61, 24, 81, 70, 30, -5, -4, 84, 84, 97])

In [42]:
a2[-1]

array([62, 11, 97])

In [43]:
a2[1,2]

97

In [54]:
a2[0,1] = -1
a2

array([[33, -1, 31],
       [62, 11, 97]])

In [55]:
a2[0,-1] = 999
a2

array([[ 33,  -1, 999],
       [ 62,  11,  97]])

## 5.2 Slicing

In [56]:
a1

array([61, 24, 81, 70, 30, -5, -4, 84, 84, 97])

In [57]:
a1[:5]

array([61, 24, 81, 70, 30])

In [58]:
a1[5:]

array([-5, -4, 84, 84, 97])

In [59]:
a1[2:8]

array([81, 70, 30, -5, -4, 84])

In [60]:
a1[2:8:2]

array([81, 30, -4])

In [61]:
a1[::3]

array([61, 70, -4, 97])

In [44]:
a1[1::2]

array([24, 70, -5, 84, 97])

In [55]:
a1[::-1]

mySentence = "hello world"
myArrSent = [x for x in mySentence]
''.join([x for x in myArrSent[::-1]])

'dlrow olleh'

In [62]:
# mySentence[:1,]

In [162]:
a2

array([[33, 12, 31],
       [62, 99, 97]])

In [164]:
a2[:1,] #33 12 31
# a2

array([[33, 12, 31]])

In [165]:
a2[:2,] #33 12 31, 62 99 97
# a2

array([[33, 12, 31],
       [62, 99, 97]])

In [166]:
a2[1:,] #62 99 97
a2

array([[33, 12, 31],
       [62, 99, 97]])

In [159]:
a2[0:]
a2

array([[33, 12, 31],
       [62, 99, 97]])

In [167]:
a2[1:,2:] #97
a2

array([[33, 12, 31],
       [62, 99, 97]])

In [168]:
a2[::-1,] # 62 99 97, 33 12 31
a2

array([[33, 12, 31],
       [62, 99, 97]])

In [173]:
a2[:,::-1]   # 31 12 33 97 99 62

array([[31, 12, 33],
       [97, 99, 62]])

In [78]:
# Slicing von Spalten
a2

array([[33, 12, 31],
       [62, 11, 97]])

In [174]:
a2[:,0]
#33 63

array([33, 62])

In [171]:
a2[:,1]
#12 99

array([[33, 12, 31],
       [62, 99, 97]])

In [172]:
a2[:,2]
#31 97

array([[33, 12, 31],
       [62, 99, 97]])

In [82]:
# Slicing von Zeilen
a2

array([[33, 12, 31],
       [62, 11, 97]])

In [177]:
# Slicing von Spalten
a2[0,:]

array([33, 12, 31])

In [84]:
a2[1,:]

array([62, 11, 97])

In [85]:
# kürzer:
a2[0]

array([33, 12, 31])

In [86]:
a2[1]

array([62, 11, 97])

In [87]:
a3

array([[[39, 47, 11, 73, 69],
        [30, 42, 85, 67, 31],
        [98, 58, 68, 51, 69],
        [89, 24, 71, 71, 56]],

       [[71, 60, 64, 73, 12],
        [60, 16, 30, 82, 48],
        [27, 13, 98, 69, 23],
        [18, 99, 62, 11, 93]],

       [[69, 80, 53, 17, 56],
        [44, 87, 90, 45, 59],
        [13, 11, 15, 63, 13],
        [63, 72, 27, 99, 53]]])

In [88]:
a3[2]

array([[69, 80, 53, 17, 56],
       [44, 87, 90, 45, 59],
       [13, 11, 15, 63, 13],
       [63, 72, 27, 99, 53]])

In [190]:
a4

array([[[[43, 83],
         [71, 23],
         [57, 24],
         [81, 87],
         [96, 71]],

        [[49, 94],
         [89, 91],
         [62, 33],
         [35, 98],
         [69, 50]]],


       [[[38, 24],
         [54, 74],
         [98, 80],
         [18, 97],
         [10, 17]],

        [[97, 72],
         [20, 90],
         [17, 44],
         [44, 42],
         [14, 50]]],


       [[[37, 16],
         [82, 81],
         [21, 43],
         [42, 57],
         [32, 71]],

        [[97, 46],
         [53, 95],
         [44, 74],
         [56, 87],
         [12, 10]]]])

In [189]:
a4[1:2,0:3,]

array([[[[38, 24],
         [54, 74],
         [98, 80],
         [18, 97],
         [10, 17]],

        [[97, 72],
         [20, 90],
         [17, 44],
         [44, 42],
         [14, 50]]]])

In [91]:
a4[1:2,0:3,1:2]

array([[[[54, 74]],

        [[20, 90]]]])

In [92]:
a2  # Slices erzeugen Views, keine Kopien!

array([[33, 12, 31],
       [62, 11, 97]])

In [93]:
a_test = a2[:2,:2]
a_test

array([[33, 12],
       [62, 11]])

In [94]:
a_test[1,1] = 99
a_test

array([[33, 12],
       [62, 99]])

In [95]:
a2

array([[33, 12, 31],
       [62, 99, 97]])

In [96]:
# copy erzeugt Kopie (später wird auch "deepcopy" benötigt)
a_test = a2[:2,:2].copy()
a_test

array([[33, 12],
       [62, 99]])

In [97]:
a_test[1,1] = 77
a_test

array([[33, 12],
       [62, 77]])

In [98]:
a2

array([[33, 12, 31],
       [62, 99, 97]])

## 5.3 Das Schlüsselwort 

In [191]:
m = np.array([2,3,5,7,11,13,17,19])
m

array([ 2,  3,  5,  7, 11, 13, 17, 19])

In [100]:
m.shape

(8,)

In [196]:
n = m.reshape((8,))
n

array([ 2,  3,  5,  7, 11, 13, 17, 19])

In [102]:
n.shape

(1, 8)

In [194]:
# Zeilenvektor
o = m[np.newaxis, :]

In [104]:
o.shape

(1, 8)

In [105]:
o

array([[ 2,  3,  5,  7, 11, 13, 17, 19]])

In [106]:
p = m[:, np.newaxis]

In [107]:
p.shape

(8, 1)

In [108]:
p

array([[ 2],
       [ 3],
       [ 5],
       [ 7],
       [11],
       [13],
       [17],
       [19]])

## 5.4 Verbinden von Arrays

In [197]:
m1 = np.array([1,2,3])
m2 = np.array([4,5,6,7])
m3 = np.array([8,9])

In [111]:
np.concatenate([m1,m2,m3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
n1 = np.mgrid[3:7, 8:11]
n1

array([[[ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6]],

       [[ 8,  9, 10],
        [ 8,  9, 10],
        [ 8,  9, 10],
        [ 8,  9, 10]]])

In [113]:
n2 = np.mgrid[7:11, 11:14]
n2

array([[[ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]],

       [[11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13]]])

In [114]:
n3 = np.concatenate([n1, n2])
n3

array([[[ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6]],

       [[ 8,  9, 10],
        [ 8,  9, 10],
        [ 8,  9, 10],
        [ 8,  9, 10]],

       [[ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]],

       [[11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13]]])

In [206]:
n4 = np.concatenate([n1, n2], axis=1)
n4

array([[[ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]],

       [[ 8,  9, 10],
        [ 8,  9, 10],
        [ 8,  9, 10],
        [ 8,  9, 10],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13]]])

In [207]:
o1 = np.arange(1,4)
o2 = np.array([[4,5,6],[7,8,9],[10,11,12]])
o1, o2
o1.reshape((3,1))

array([[1],
       [2],
       [3]])

In [208]:
# o3 = np.concatenate([o1,o2])

In [209]:
# Vertikaler Stapel
o = np.vstack([o1,o2])
o

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [210]:
# Horizontaler Stapel
np.hstack([o1.reshape((3,1)),o2])

array([[ 1,  4,  5,  6],
       [ 2,  7,  8,  9],
       [ 3, 10, 11, 12]])

In [211]:
# weitere Achse mit np.dstack

## 5.5 Zerlegen von Arrays

In [212]:
o

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [213]:
np.split(o, [1])

[array([[1, 2, 3]]),
 array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])]

In [124]:
np.split(o, [1,2])

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [215]:
np.split(o, [1,3])

[array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12]])]

In [216]:
o

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [131]:
# vertikales Zerlegen
np.vsplit(o,[2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [222]:
# horizontales Zerlegen
np.hsplit(o,[2])

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

## 5.6 Vektorisierung (UFunctions)

In [223]:
# Beispiel zum Einstieg

def testrechnung(zahl):
    return np.sin(np.pi*zahl)

def testfunktion(zahlen):
    l = len(zahlen)
    result = np.empty(l)
    for i in range(l):
        result[i] = testrechnung(zahlen[i])
    return result

In [224]:
zahlen = np.random.randint(1,100, size=10)
testfunktion(zahlen)

array([ 1.95819692e-15, -2.44929360e-15,  1.86183452e-14, -9.79717439e-16,
       -1.95943488e-15, -1.71450552e-15, -2.35181704e-14,  2.84179955e-14,
        5.38968388e-15, -2.54776053e-14])

In [225]:
zahlen = np.random.randint(1,100, size=1000000)
%timeit testfunktion(zahlen)

2.51 s ± 8.74 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [226]:
schneller = np.vectorize(testrechnung)
def testfunktion2(zahlen):
    return schneller(zahlen)

In [227]:
zahlen = np.random.randint(1,100, size=1000000)
%timeit testfunktion2(zahlen)

919 ms ± 15.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
zahlen = np.random.randint(1,100, size=10)
testfunktion(zahlen), testfunktion2(zahlen)

In [ ]:
# weitere eingebaute Vektorisierungen:
a = np.arange(1,20)
a

In [ ]:
print(a+1)

In [ ]:
print(a*2)

In [ ]:
a = np.mgrid[1:6,4:7]
a

In [ ]:
b = np.mgrid[0:5,2:5]
b

In [ ]:
a*b

In [ ]:
2**a

In [ ]:
a*2-b

In [ ]:
np.exp(a)

In [ ]:
# wenn statt * multiply (analog +, - , //, % ...) verwendet wird, lässt sich die
# Ausgabe vorgeben:

in_data = np.arange(10)
in_data

In [ ]:
out_data = np.zeros(20)
out_data

In [ ]:
np.multiply(in_data, 2, out=out_data[5:15])

In [ ]:
out_data

## 5.7 Reduktion und Akkumulation

In [228]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [229]:
np.multiply.reduce(a)

24

In [230]:
np.add.reduce(a)

10

In [231]:
a

array([1, 2, 3, 4])

In [232]:
np.add.accumulate(a)

array([ 1,  3,  6, 10])

In [233]:
np.multiply.accumulate(a)

array([ 1,  2,  6, 24])

In [234]:
np.multiply.outer(a,a)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [235]:
np.add.outer(a,a)

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

## 5.8 Aggregation

In [236]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [237]:
sum(a)

5050

In [238]:
np.sum(a)

5050

In [239]:
testarray = np.random.rand(100000)

In [240]:
%timeit sum(testarray)

8.24 ms ± 445 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [241]:
%timeit np.sum(testarray)

23.8 µs ± 2.24 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [242]:
print(np.min(a), np.min(testarray))

1 3.2296824094002474e-06


In [243]:
print(np.max(a), np.max(testarray))

100 0.9999601363484044


In [ ]:
# Mittelwert
print(np.mean(a), np.mean(testarray))

In [ ]:
# Standardabweichung
print(np.std(a), np.std(testarray))

In [ ]:
# Varianz
print(np.var(a), np.var(testarray))

In [ ]:
# Median
print(np.median(a), np.median(testarray))

In [244]:
# Index des kleinsten Wertes
print(np.argmin(a), np.argmin(testarray))

0 37169


In [ ]:
print(a[np.argmin(a)], testarray[np.argmin(testarray)])

In [ ]:
# Index des größten Wertes
print(np.argmax(a), np.argmax(testarray))

In [ ]:
print(a[np.argmax(a)], testarray[np.argmax(testarray)])

## 5.9 Test auf True

In [245]:
a1 = [False,False,False,False,False,False,False,False,False,False]
np.any(a1)

False

In [246]:
a2 = [False,False,False,True,False,False,False,False,False,False]
np.any(a2)

True

In [247]:
a3 = [True,False,True,True,True,True,True,True,True]
np.all(a3)

False

In [248]:
a3 = [True,True,True,True,True,True,True,True,True]
np.all(a3)

True

## 5.10 Broadcasting

In [249]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([2,3,4])

In [250]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [251]:
m1 + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [252]:
m2 - 1

array([1, 2, 3])

In [253]:
m1 + m2

array([[ 3,  5,  7],
       [ 6,  8, 10]])

In [254]:
m1 * m2

array([[ 2,  6, 12],
       [ 8, 15, 24]])

In [255]:
m1 * m2 * 2

array([[ 4, 12, 24],
       [16, 30, 48]])

In [256]:
m3 = np.random.random(10)
m3

array([0.87003393, 0.42228754, 0.84003392, 0.06494444, 0.90860489,
       0.49112088, 0.9594652 , 0.74792705, 0.65780337, 0.87074171])

In [257]:
m3.mean()

0.6832962916746044

In [258]:
m3 = m3 - m3.mean()
m3

array([ 0.18673764, -0.26100875,  0.15673762, -0.61835185,  0.2253086 ,
       -0.19217541,  0.2761689 ,  0.06463075, -0.02549293,  0.18744542])

In [259]:
m3.mean()

3.3306690738754695e-17

In [260]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [261]:
m1 < 3

array([[ True,  True, False],
       [False, False, False]])

In [262]:
m1 >= 4

array([[False, False, False],
       [ True,  True,  True]])

In [263]:
m1 < m2

array([[ True,  True,  True],
       [False, False, False]])

In [264]:
m2 <= m1

array([[False, False, False],
       [ True,  True,  True]])

In [265]:
np.count_nonzero([1,2,0,3,2])

4

In [266]:
np.count_nonzero(m1 < m2)

3

In [267]:
np.sum(m1 < 3)  # True 1 und False 0

2

In [268]:
np.any(m2 > 3)

True

In [269]:
np.any(m2 > 4)

False

In [270]:
np.all(m1 < 10)

True

In [271]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [272]:
np.all(m1 < 4, axis = 0)

array([False, False, False])

In [273]:
np.all(m1 < 4, axis = 1)

array([ True, False])

In [274]:
m1 < 5

array([[ True,  True,  True],
       [ True, False, False]])

## 5.11 Maskierung

In [275]:
m1[m1 < 5]

array([1, 2, 3, 4])

In [276]:
n1 = np.array([1,1,0,1,0,0,1,0], dtype = bool)
n2 = np.array([1,0,1,0,0,0,1,1], dtype = bool)

In [277]:
n1, n2

(array([ True,  True, False,  True, False, False,  True, False]),
 array([ True, False,  True, False, False, False,  True,  True]))

In [278]:
n1 & n2

array([ True, False, False, False, False, False,  True, False])

In [279]:
n1 | n2

array([ True,  True,  True,  True, False, False,  True,  True])

In [280]:
n1 ^ n2

array([False,  True,  True,  True, False, False, False,  True])

## 5.12 Fancy Indexing

In [282]:
beispiel = np.arange(20)+1
beispiel

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [283]:
index_liste = [1,2,4,6,10,12,16,18]

In [284]:
beispiel[index_liste]

array([ 2,  3,  5,  7, 11, 13, 17, 19])

In [281]:
index_liste2 = np.array([[3,4,5],[7,8,9]])
index_liste2

array([[3, 4, 5],
       [7, 8, 9]])

In [285]:
beispiel[index_liste2]

array([[ 4,  5,  6],
       [ 8,  9, 10]])

In [286]:
beispiel2 = np.mgrid[1:5,5:10]
beispiel2

array([[[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9]]])

In [287]:
index_liste3 = [3,2,1]

In [288]:
beispiel2[0,index_liste3]

array([[4, 4, 4, 4, 4],
       [3, 3, 3, 3, 3],
       [2, 2, 2, 2, 2]])

In [291]:
beispiel2[1,index_liste3]
index_liste3[1:]

[2, 1]

In [290]:
beispiel2[0,index_liste3[1:]]

array([[3, 3, 3, 3, 3],
       [2, 2, 2, 2, 2]])

In [292]:
beispiel2

array([[[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9]]])

In [293]:
beispiel2[0,index_liste3[1:]] = [[1,2,3,4,5],[6,7,8,9,10]]
beispiel2

array([[[ 1,  1,  1,  1,  1],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 4,  4,  4,  4,  4]],

       [[ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9]]])

## 5.13 Sortieren

In [294]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [295]:
np.random.shuffle(a)
a

array([ 7, 17,  9,  5, 10,  6, 18,  2,  4, 14,  1, 12, 15, 16, 13,  3, 19,
        8, 11,  0])

In [296]:
np.sort(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [297]:
beispiel2

array([[[ 1,  1,  1,  1,  1],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 4,  4,  4,  4,  4]],

       [[ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9]]])

In [298]:
np.sort(beispiel2)

array([[[ 1,  1,  1,  1,  1],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 4,  4,  4,  4,  4]],

       [[ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9]]])

In [299]:
np.sort(beispiel2, axis = 0)

array([[[ 1,  1,  1,  1,  1],
        [ 5,  6,  7,  8,  9],
        [ 1,  2,  3,  4,  5],
        [ 4,  4,  4,  4,  4]],

       [[ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9]]])

In [300]:
np.sort(beispiel2, axis = 1)

array([[[ 1,  1,  1,  1,  1],
        [ 1,  2,  3,  4,  4],
        [ 4,  4,  4,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9]]])

In [301]:
np.sort(beispiel2, axis = None)

array([ 1,  1,  1,  1,  1,  1,  2,  3,  4,  4,  4,  4,  4,  4,  5,  5,  5,
        5,  5,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,
        9,  9,  9,  9,  9, 10])

In [302]:
a

array([ 7, 17,  9,  5, 10,  6, 18,  2,  4, 14,  1, 12, 15, 16, 13,  3, 19,
        8, 11,  0])

In [303]:
indices = np.argsort(a)
indices

array([19, 10,  7, 15,  8,  3,  5,  0, 17,  2,  4, 18, 11, 14,  9, 12, 13,
        1,  6, 16])

In [304]:
a[indices]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [305]:
a

array([ 7, 17,  9,  5, 10,  6, 18,  2,  4, 14,  1, 12, 15, 16, 13,  3, 19,
        8, 11,  0])

In [306]:
np.partition(a, 5) # Teilfunktion von Quicksort

array([ 1,  2,  3,  0,  4,  5,  6,  7, 18, 17, 10, 12, 15, 16, 13,  9, 19,
        8, 11, 14])

In [307]:
np.argpartition(a,5)

array([10,  7, 15, 19,  8,  3,  5,  0,  6,  1,  4, 11, 12, 13, 14,  2, 16,
       17, 18,  9])

In [308]:
a[np.argpartition(a,5)]

array([ 1,  2,  3,  0,  4,  5,  6,  7, 18, 17, 10, 12, 15, 16, 13,  9, 19,
        8, 11, 14])