# 5. Numerical Python mit NumPy 

In [1]:
import numpy as np

## 5.1 NumPy Arrays Grundlagen

In [2]:
a = [1,2,3,4,5,6,7,8,9]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
b = np.array(a)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np?

Type:        module
String form: <module 'numpy' from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py'>
File:        /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets 

In [5]:
b[3] = 2.71

In [6]:
b

array([1, 2, 3, 2, 5, 6, 7, 8, 9])

In [ ]:
b?

In [7]:
c = np.array([2,3,4,3.1415,1])

In [8]:
c

array([2.    , 3.    , 4.    , 3.1415, 1.    ])

In [9]:
c.sort()
c

array([1.    , 2.    , 3.    , 3.1415, 4.    ])

In [10]:
d = np.array(range(100))
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
t = (100,)

In [12]:
type(t)

tuple

In [13]:
d.shape

(100,)

In [14]:
d.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [15]:
d.reshape(2,5,10)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [16]:
d.reshape(100,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
np.zeros(10, dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [18]:
np.ones(10, dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.full((4,7),4711)

array([[4711, 4711, 4711, 4711, 4711, 4711, 4711],
       [4711, 4711, 4711, 4711, 4711, 4711, 4711],
       [4711, 4711, 4711, 4711, 4711, 4711, 4711],
       [4711, 4711, 4711, 4711, 4711, 4711, 4711]])

In [20]:
e = np.array([range(index, index+13,3) for index in [9,8,5,4]])

In [21]:
e

array([[ 9, 12, 15, 18, 21],
       [ 8, 11, 14, 17, 20],
       [ 5,  8, 11, 14, 17],
       [ 4,  7, 10, 13, 16]])

In [22]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [23]:
np.arange(5,17,2,dtype=int)

array([ 5,  7,  9, 11, 13, 15])

In [24]:
np.linspace(5,25,10)

array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
       16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ])

In [25]:
np.random.random(19)

array([0.02457893, 0.88995706, 0.03543573, 0.40019896, 0.49901336,
       0.23588884, 0.06114474, 0.86560098, 0.67807504, 0.81277315,
       0.62656346, 0.31134023, 0.81243785, 0.62443092, 0.58640783,
       0.2980255 , 0.83230053, 0.52357238, 0.2959375 ])

In [26]:
np.random.random((5,5))

array([[0.87701689, 0.73909628, 0.82246556, 0.07335741, 0.78360742],
       [0.41280115, 0.02039375, 0.67270415, 0.85788066, 0.63476492],
       [0.19792351, 0.94827497, 0.68717603, 0.35197987, 0.16480987],
       [0.28933513, 0.41243644, 0.31674819, 0.24324203, 0.40167544],
       [0.3065823 , 0.97970394, 0.42741424, 0.71541347, 0.78527166]])

In [27]:
mittelwert = -5
standardabweichung = 5
anzahl = 100
np.random.normal(mittelwert, standardabweichung, anzahl)

array([ -2.61912855,  -1.62423444,  -1.02365712,  -5.43849269,
        -0.49553435,   5.28785115, -18.87774562,  -5.94947456,
        -5.03149724,  -4.99276539,   2.15576548,  -3.80030962,
        -6.42269658, -16.77140473,   1.02579703,  -3.97934117,
        -7.03412522,  -1.70219073, -11.12519986,  -0.2669321 ,
       -10.90368542,  -5.90454762,  -6.16851457, -13.66052253,
        -6.01616094, -11.00537102,  -5.17916627,  -4.23716288,
        -1.46109406, -12.10623854,  -2.04801838, -11.4388306 ,
         0.02247544,  -1.3594589 ,   1.79561013, -17.291287  ,
         0.06749802,  -9.56669789,  -6.33626118,  -8.20311814,
        -7.92919013,  -7.18596285, -11.91236603, -12.73276372,
         9.05750139,  -1.70301427,   2.54693187, -11.62749446,
        -1.62423821,  -7.34213525,   0.31238873,  -4.80201614,
        -8.7445271 ,  -6.06508625,  -0.09554308,  -2.89957469,
       -11.94732156, -11.75099927, -11.67456676, -10.04129444,
        -5.62877807,  -9.81268301,  -3.73015069,  -0.67

In [28]:
np.random.normal(mittelwert, standardabweichung, (3,5,4))

array([[[ -4.26733581, -12.37460656,  -5.26113928,   1.04255214],
        [ -3.64775345,  -4.93520422, -11.57273649, -12.473446  ],
        [ -6.53846971,  -7.93855878,  -4.226059  ,  -6.13195679],
        [ -5.75418793,  -1.69389094,  -0.72459349,  -1.13269228],
        [ -7.02065425, -10.91859062,   0.80307486,  -5.84255134]],

       [[ -2.62403874,  -4.52794066,  -0.97868926,  -7.18564246],
        [  1.96686382, -12.92279375, -12.54618116,  -3.43083877],
        [ -4.44759545,  -7.54611281,  -4.46152593, -12.72406521],
        [ -7.34188572,   4.12383336,  -8.35798531,  -6.47993471],
        [ -5.41471845,  -2.45002527,  -6.74533456,  -6.64301192]],

       [[-16.53437691,  -3.90431585,  -5.23389031,  -6.45724531],
        [-11.43220001,  -7.2195472 ,  -2.23612393,  -1.70297113],
        [ -0.73811198,  -0.94521455, -13.09152321,   6.8075454 ],
        [-14.10750204,  -3.45054733, -10.16613357,  -6.36867655],
        [  3.62847668,   4.16148665,   0.1555322 ,  -0.27664226]]])

In [ ]:
np.random.seed(42)
von = 10  # inklusive
bis = 100 # exklusive
a1 = np.random.randint(von, bis, 10)
a2 = np.random.randint(von, bis, (2,3))
a3 = np.random.randint(von, bis, (3,4,5))
a4 = np.random.randint(von, bis, (3,2,5,2))
a5 = np.random.randint(von, bis, (4,5,6,2,2))
myArrays = [a1,a2,a3,a4,a5]

In [ ]:
for i in range(len(myArrays)):
    print("a{0:}: Dimension {1:}, Size {2:3d}, Itemsize {3:}, NBytes {4:4d}, Shape {5:}".format(
        i+1,myArrays[i].ndim,
        myArrays[i].size,
        myArrays[i].itemsize,
        myArrays[i].nbytes,
        myArrays[i].shape))

In [ ]:
a1

In [ ]:
a1[5]

In [ ]:
a1[5] = -5
a1

In [ ]:
a1[-1]

In [ ]:
a1[-4] = -4
a1

In [ ]:
a2

In [ ]:
a2[1,2]

In [ ]:
a2[0,1] = -1
a2

In [ ]:
a2[0,-1] = 999
a2

## 5.2 Slicing

In [ ]:
a1

In [ ]:
a1[:5]

In [ ]:
a1[5:]

In [ ]:
a1[2:8]

In [ ]:
a1[2:8:2]

In [ ]:
a1[::3]

In [ ]:
a1[1::2]

In [ ]:
a1[::-1]

In [ ]:
a1[::-2]

In [ ]:
a2

In [ ]:
a2[:1,]

In [ ]:
a2[:2,]

In [ ]:
a2[1:,]

In [ ]:
a2[0:,]

In [ ]:
a2[1:,2:]

In [ ]:
a2[::-1,]

In [ ]:
a2[:,::-1]

In [ ]:
# Slicing von Spalten
a2

In [ ]:
a2[:,0]

In [ ]:
a2[:,1]

In [ ]:
a2[:,2]

In [ ]:
# Slicing von Zeilen
a2

In [ ]:
# Slicing von Spalten
a2[0,:]

In [ ]:
a2[1,:]

In [ ]:
# kürzer:
a2[0]

In [ ]:
a2[1]

In [ ]:
a3

In [ ]:
a3[2]

In [ ]:
a4

In [ ]:
a4[1]

In [ ]:
a4[1:2,0:3,1:2]

In [ ]:
a2  # Slices erzeugen Views, keine Kopien!

In [ ]:
a_test = a2[:2,:2]
a_test

In [ ]:
a_test[1,1] = 99
a_test

In [ ]:
a2

In [ ]:
# copy erzeugt Kopie (später wird auch "deepcopy" benötigt)
a_test = a2[:2,:2].copy()
a_test

In [ ]:
a_test[1,1] = 77
a_test

In [ ]:
a2

## 5.3 Das Schlüsselwort newaxis

In [ ]:
m = np.array([2,3,5,7,11,13,17,19])

In [ ]:
m.shape

In [ ]:
n = m.reshape((1,8))
n

In [ ]:
n.shape

In [ ]:
# Zeilenvektor
o = m[np.newaxis, :]

In [ ]:
o.shape

In [ ]:
o

In [ ]:
p = m[:, np.newaxis]

In [ ]:
p.shape

In [ ]:
p

## 5.4 Verbinden von Arrays

In [ ]:
m1 = np.array([1,2,3])
m2 = np.array([4,5,6,7])
m3 = np.array([8,9])

In [ ]:
np.concatenate([m1,m2,m3])

In [ ]:
n1 = np.mgrid[3:7, 8:11]
n1

In [ ]:
n2 = np.mgrid[7:11, 11:14]
n2

In [ ]:
n3 = np.concatenate([n1, n2])
n3

In [ ]:
n4 = np.concatenate([n1, n2], axis=1)
n4

In [ ]:
o1 = np.arange(1,4)
o2 = np.array([[4,5,6],[7,8,9],[10,11,12]])
o1, o2

In [ ]:
# o3 = np.concatenate([o1,o2])

In [ ]:
# Vertikaler Stapel
o = np.vstack([o1,o2])
o

In [ ]:
# Horizontaler Stapel
np.hstack([o1.reshape((3,1)),o2])

In [ ]:
# weitere Achse mit np.dstack

## 5.5 Zerlegen von Arrays

In [ ]:
o

In [ ]:
np.split(o, [1])

In [ ]:
np.split(o, [1,2])

In [ ]:
np.split(o, [1,3])

In [ ]:
np.split(o, [1,4])

In [ ]:
# vertikales Zerlegen
np.vsplit(o,[2])

In [ ]:
# horizontales Zerlegen
np.hsplit(o,[2])

## 5.6 Vektorisierung (UFunctions)

In [ ]:
# Beispiel zum Einstieg

def testrechnung(zahl):
    return np.sin(np.pi*zahl)

def testfunktion(zahlen):
    l = len(zahlen)
    result = np.empty(l)
    for i in range(l):
        result[i] = testrechnung(zahlen[i])
    return result

In [ ]:
zahlen = np.random.randint(1,100, size=10)
testfunktion(zahlen)

In [ ]:
zahlen = np.random.randint(1,100, size=1000000)
%timeit testfunktion(zahlen)

In [ ]:
schneller = np.vectorize(testrechnung)
def testfunktion2(zahlen):
    return schneller(zahlen)

In [ ]:
zahlen = np.random.randint(1,100, size=1000000)
%timeit testfunktion2(zahlen)

In [ ]:
zahlen = np.random.randint(1,100, size=10)
testfunktion(zahlen), testfunktion2(zahlen)

In [ ]:
# weitere eingebaute Vektorisierungen:
a = np.arange(1,20)
a

In [ ]:
print(a+1)

In [ ]:
print(a*2)

In [ ]:
a = np.mgrid[1:6,4:7]
a

In [ ]:
b = np.mgrid[0:5,2:5]
b

In [ ]:
a*b

In [ ]:
2**a

In [ ]:
a*2-b

In [ ]:
np.exp(a)

In [ ]:
# wenn statt * multiply (analog +, - , //, % ...) verwendet wird, lässt sich die
# Ausgabe vorgeben:

in_data = np.arange(10)
in_data

In [ ]:
out_data = np.zeros(20)
out_data

In [ ]:
np.multiply(in_data, 2, out=out_data[5:15])

In [ ]:
out_data

## 5.7 Reduktion und Akkumulation

In [ ]:
a = np.arange(1,5)
a

In [ ]:
np.multiply.reduce(a)

In [ ]:
np.add.reduce(a)

In [ ]:
a

In [ ]:
np.add.accumulate(a)

In [ ]:
np.multiply.accumulate(a)

In [ ]:
np.multiply.outer(a,a)

In [ ]:
np.add.outer(a,a)

## 5.8 Aggregation

In [ ]:
a = np.arange(1,101)
a

In [ ]:
sum(a)

In [ ]:
np.sum(a)

In [ ]:
testarray = np.random.rand(100000)

In [ ]:
%timeit sum(testarray)

In [ ]:
%timeit np.sum(testarray)

In [ ]:
print(np.min(a), np.min(testarray))

In [ ]:
print(np.max(a), np.max(testarray))

In [ ]:
# Mittelwert
print(np.mean(a), np.mean(testarray))

In [ ]:
# Standardabweichung
print(np.std(a), np.std(testarray))

In [ ]:
# Varianz
print(np.var(a), np.var(testarray))

In [ ]:
# Median
print(np.median(a), np.median(testarray))

In [ ]:
# Index des kleinsten Wertes
print(np.argmin(a), np.argmin(testarray))

In [ ]:
print(a[np.argmin(a)], testarray[np.argmin(testarray)])

In [ ]:
# Index des größten Wertes
print(np.argmax(a), np.argmax(testarray))

In [ ]:
print(a[np.argmax(a)], testarray[np.argmax(testarray)])

## 5.9 Test auf True

In [ ]:
a1 = [False,False,False,False,False,False,False,False,False,False]
np.any(a1)

In [ ]:
a2 = [False,False,False,True,False,False,False,False,False,False]
np.any(a2)

In [ ]:
a3 = [True,False,True,True,True,True,True,True,True]
np.all(a3)

In [ ]:
a3 = [True,True,True,True,True,True,True,True,True]
np.all(a3)

## 5.10 Broadcasting

In [ ]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([2,3,4])

In [ ]:
m1

In [ ]:
m1 + 5

In [ ]:
m2 - 1

In [ ]:
m1 + m2

In [ ]:
m1 * m2

In [ ]:
m1 * m2 * 2

In [ ]:
m3 = np.random.random(10)
m3

In [ ]:
m3.mean()

In [ ]:
m3 = m3 - m3.mean()
m3

In [ ]:
m3.mean()

In [ ]:
m1

In [ ]:
m1 < 3

In [ ]:
m1 >= 4

In [ ]:
m1 < m2

In [ ]:
m2 <= m1

In [ ]:
np.count_nonzero([1,2,0,3,2])

In [ ]:
np.count_nonzero(m1 < m2)

In [ ]:
np.sum(m1 < 3)  # True 1 und False 0

In [ ]:
np.any(m2 > 3)

In [ ]:
np.any(m2 > 4)

In [ ]:
np.all(m1 < 10)

In [ ]:
m1

In [ ]:
np.all(m1 < 4, axis = 0)

In [ ]:
np.all(m1 < 4, axis = 1)

In [ ]:
m1 < 5

## 5.11 Maskierung

In [ ]:
m1[m1 < 5]  

In [ ]:
n1 = np.array([1,1,0,1,0,0,1,0], dtype = bool)
n2 = np.array([1,0,1,0,0,0,1,1], dtype = bool)

In [ ]:
n1, n2

In [ ]:
n1 & n2

In [ ]:
n1 | n2

In [ ]:
n1 ^ n2

## 5.12 Fancy Indexing

In [ ]:
beispiel = np.arange(20)+1
beispiel

In [ ]:
index_liste = [1,2,4,6,10,12,16,18]

In [ ]:
beispiel[index_liste]

In [ ]:
index_liste2 = np.array([[3,4,5],[7,8,9]])
index_liste2

In [ ]:
beispiel[index_liste2]

In [ ]:
beispiel2 = np.mgrid[1:5,5:10]
beispiel2

In [ ]:
index_liste3 = [3,2,1]

In [ ]:
beispiel2[0,index_liste3]

In [ ]:
beispiel2[1,index_liste3]

In [ ]:
beispiel2[0,index_liste3[1:]]

In [ ]:
beispiel2

In [ ]:
beispiel2[0,index_liste3[1:]] = [[1,2,3,4,5],[6,7,8,9,10]]
beispiel2

## 5.13 Sortieren

In [ ]:
a = np.arange(20)
a

In [ ]:
np.random.shuffle(a)
a

In [ ]:
np.sort(a)

In [ ]:
beispiel2

In [ ]:
np.sort(beispiel2)

In [ ]:
np.sort(beispiel2, axis = 0)

In [ ]:
np.sort(beispiel2, axis = 1)

In [ ]:
np.sort(beispiel2, axis = None)

In [ ]:
a

In [ ]:
indices = np.argsort(a)
indices

In [ ]:
a[indices]

In [ ]:
a

In [ ]:
np.partition(a, 5) # Teilfunktion von Quicksort

In [ ]:
np.argpartition(a,5)

In [ ]:
a[np.argpartition(a,5)]