# 5. Numerical Python mit NumPy 

In [4]:
import numpy as np

## 5.1 NumPy Arrays Grundlagen

In [5]:
a = [1,2,3,4,5,6,7,8,9]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
b = np.array(a)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np?

Type:        module
String form: <module 'numpy' from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py'>
File:        /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets 

In [7]:
b[3] = 2.71

In [6]:
b

array([1, 2, 3, 2, 5, 6, 7, 8, 9])

In [ ]:
b?

In [7]:
c = np.array([2,3,4,3.1415,1])

In [8]:
c

array([2.    , 3.    , 4.    , 3.1415, 1.    ])

In [9]:
c.sort()
c

array([1.    , 2.    , 3.    , 3.1415, 4.    ])

In [15]:
d = np.array([*range(100)])
d.shape

(100,)

In [11]:
t = (100,)

In [12]:
type(t)

tuple

In [13]:
d.shape

(100,)

In [17]:
d.reshape(5,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [25]:
d= d.reshape(2,5,10)
d

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [24]:
d[1][0]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [27]:
d=d.reshape(100,)

In [30]:
np.zeros(10, dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [28]:
np.ones(10, dtype=str)

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [19]:
np.full((4,7),4711)

array([[4711, 4711, 4711, 4711, 4711, 4711, 4711],
       [4711, 4711, 4711, 4711, 4711, 4711, 4711],
       [4711, 4711, 4711, 4711, 4711, 4711, 4711],
       [4711, 4711, 4711, 4711, 4711, 4711, 4711]])

In [20]:
e = np.array([range(index, index+13,3) for index in [9,8,5,4]])

In [21]:
e

array([[ 9, 12, 15, 18, 21],
       [ 8, 11, 14, 17, 20],
       [ 5,  8, 11, 14, 17],
       [ 4,  7, 10, 13, 16]])

In [22]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [23]:
np.arange(5,17,2,dtype=int)

array([ 5,  7,  9, 11, 13, 15])

In [34]:
np.linspace(5,25,10)

array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
       16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ])

In [25]:
np.random.random(19)

array([0.02457893, 0.88995706, 0.03543573, 0.40019896, 0.49901336,
       0.23588884, 0.06114474, 0.86560098, 0.67807504, 0.81277315,
       0.62656346, 0.31134023, 0.81243785, 0.62443092, 0.58640783,
       0.2980255 , 0.83230053, 0.52357238, 0.2959375 ])

In [26]:
np.random.random((5,5))

array([[0.87701689, 0.73909628, 0.82246556, 0.07335741, 0.78360742],
       [0.41280115, 0.02039375, 0.67270415, 0.85788066, 0.63476492],
       [0.19792351, 0.94827497, 0.68717603, 0.35197987, 0.16480987],
       [0.28933513, 0.41243644, 0.31674819, 0.24324203, 0.40167544],
       [0.3065823 , 0.97970394, 0.42741424, 0.71541347, 0.78527166]])

In [36]:
mittelwert = -5
standardabweichung = 5
anzahl = 100
np.random.normal(mittelwert, standardabweichung, anzahl)

array([ -5.1040297 ,  -7.39629983,   2.9962644 ,   0.8464039 ,
        -9.52236718,  -9.11059258,  -4.40373826,   2.47814103,
       -10.4074102 ,   2.4935435 ,   5.64372527,  -0.86010131,
        -8.6314141 ,   5.34833656,  -8.11153744, -12.32501777,
        -3.3718758 ,  -1.90185408, -12.94140892, -15.21432756,
        -6.8596566 ,  -7.67039265,  -0.65710146,   1.24469117,
        -1.58244097,  -8.53911028,  -1.20026184,  -2.5644226 ,
        -0.45991666,  -2.22630833,  -4.71292414,  -6.26257921,
        -6.28120273,  -0.97195213, -10.16928744,  -3.05686137,
        -4.74609975,  -8.09303394,  -2.40571861,  -0.89009148,
        -5.08022913,  -3.94391984,  -2.9506928 ,  -7.51907556,
        -1.51394794,  -6.82578553,   0.5240585 ,  -2.94279712,
        -2.2276384 ,  -5.30899588, -14.10451808,  -1.52481956,
         0.91986124,  -7.68632916,  -5.46387627,   0.82731365,
        -5.84715818,   3.97863556,  -6.11195813,   1.12582257,
       -12.91776212,   4.93463431,  -1.72281852, -10.80

In [42]:
z = np.random.normal(mittelwert, standardabweichung, (3,5,4))
z[2]

array([[ -7.39156493,  -3.9955099 , -11.30756582, -10.71498517],
       [-12.50547402,  -3.22785499,   2.41226749,  -0.92374565],
       [ -9.46466928,  -3.77728648, -11.56850382,  -0.90544766],
       [-10.78487468,  -1.83031367,  -9.97448633, -13.3495495 ],
       [ -3.08081942,  -9.39336929, -11.38841434,  -5.32399721]])

In [46]:
np.random.seed(42)
von = 10  # inklusive
bis = 100 # exklusive
a1 = np.random.randint(von, bis, 10)
a2 = np.random.randint(von, bis, (2,3))
a3 = np.random.randint(von, bis, (3,4,5))
a4 = np.random.randint(von, bis, (3,2,5,2))
a5 = np.random.randint(von, bis, (4,5,3,2,2))
myArrays = [a1,a2,a3,a4,a5]
a5

array([[[[[14, 99],
          [23, 36]],

         [[18, 88],
          [24, 99]],

         [[51, 86],
          [60, 72]]],


        [[[61, 13],
          [32, 24]],

         [[52, 38],
          [45, 22]],

         [[41, 80],
          [68, 95]]],


        [[[37, 75],
          [51, 54]],

         [[71, 66],
          [15, 37]],

         [[37, 53],
          [93, 39]]],


        [[[71, 84],
          [98, 71]],

         [[10, 36],
          [71, 86]],

         [[12, 79],
          [81, 36]]],


        [[[18, 71],
          [46, 60]],

         [[53, 33],
          [88, 68]],

         [[41, 97],
          [61, 71]]]],



       [[[[67, 61],
          [21, 48]],

         [[11, 12],
          [65, 90]],

         [[68, 11],
          [11, 63]]],


        [[[96, 10],
          [28, 11]],

         [[62, 53],
          [99, 41]],

         [[79, 41],
          [77, 64]]],


        [[[84, 65],
          [26, 47]],

         [[33, 78],
          [79, 95]],

         [[20, 25]

In [44]:
for i in range(len(myArrays)):
    print("a{0:}: Dimension {1:}, Size {2:3d}, Itemsize {3:}, NBytes {4:4d}, Shape {5:}".format(
        i+1,myArrays[i].ndim,
        myArrays[i].size,
        myArrays[i].itemsize,
        myArrays[i].nbytes,
        myArrays[i].shape))

a1: Dimension 1, Size  10, Itemsize 8, NBytes   80, Shape (10,)
a2: Dimension 2, Size   6, Itemsize 8, NBytes   48, Shape (2, 3)
a3: Dimension 3, Size  60, Itemsize 8, NBytes  480, Shape (3, 4, 5)
a4: Dimension 4, Size  60, Itemsize 8, NBytes  480, Shape (3, 2, 5, 2)
a5: Dimension 5, Size 480, Itemsize 8, NBytes 3840, Shape (4, 5, 6, 2, 2)


In [47]:
a1

array([61, 24, 81, 70, 30, 92, 96, 84, 84, 97])

In [48]:
a1[5]

92

In [49]:
a1[5] = -5
a1

array([61, 24, 81, 70, 30, -5, 96, 84, 84, 97])

In [50]:
a1[-1]

97

In [51]:
a1[-4] = -4
a1

array([61, 24, 81, 70, 30, -5, -4, 84, 84, 97])

In [52]:
a2

array([[33, 12, 31],
       [62, 11, 97]])

In [53]:
a2[1,2]

97

In [54]:
a2[0,1] = -1
a2

array([[33, -1, 31],
       [62, 11, 97]])

In [55]:
a2[0,-1] = 999
a2

array([[ 33,  -1, 999],
       [ 62,  11,  97]])

## 5.2 Slicing

In [56]:
a1

array([61, 24, 81, 70, 30, -5, -4, 84, 84, 97])

In [57]:
a1[:5]

array([61, 24, 81, 70, 30])

In [58]:
a1[5:]

array([-5, -4, 84, 84, 97])

In [59]:
a1[2:8]

array([81, 70, 30, -5, -4, 84])

In [60]:
a1[2:8:2]

array([81, 30, -4])

In [61]:
a1[::3]

array([61, 70, -4, 97])

In [62]:
a1[1::2]

array([24, 70, -5, 84, 97])

In [ ]:
a1[::-1]

In [ ]:
a1[::-2]

In [ ]:
a2

In [ ]:
a2[:1,]

In [ ]:
a2[:2,]

In [ ]:
a2[1:,]

In [ ]:
a2[0:,]

In [ ]:
a2[1:,2:]

In [ ]:
a2[::-1,]

In [ ]:
a2[:,::-1]

In [ ]:
# Slicing von Spalten
a2

In [ ]:
a2[:,0]

In [ ]:
a2[:,1]

In [ ]:
a2[:,2]

In [ ]:
# Slicing von Zeilen
a2

In [ ]:
# Slicing von Spalten
a2[0,:]

In [ ]:
a2[1,:]

In [ ]:
# kürzer:
a2[0]

In [ ]:
a2[1]

In [ ]:
a3

In [ ]:
a3[2]

In [ ]:
a4

In [ ]:
a4[1]

In [ ]:
a4[1:2,0:3,1:2]

In [ ]:
a2  # Slices erzeugen Views, keine Kopien!

In [ ]:
a_test = a2[:2,:2]
a_test

In [ ]:
a_test[1,1] = 99
a_test

In [ ]:
a2

In [ ]:
# copy erzeugt Kopie (später wird auch "deepcopy" benötigt)
a_test = a2[:2,:2].copy()
a_test

In [ ]:
a_test[1,1] = 77
a_test

In [ ]:
a2

## 5.3 Das Schlüsselwort newaxis

In [ ]:
m = np.array([2,3,5,7,11,13,17,19])

In [ ]:
m.shape

In [ ]:
n = m.reshape((1,8))
n

In [ ]:
n.shape

In [ ]:
# Zeilenvektor
o = m[np.newaxis, :]

In [ ]:
o.shape

In [ ]:
o

In [ ]:
p = m[:, np.newaxis]

In [ ]:
p.shape

In [ ]:
p

## 5.4 Verbinden von Arrays

In [ ]:
m1 = np.array([1,2,3])
m2 = np.array([4,5,6,7])
m3 = np.array([8,9])

In [ ]:
np.concatenate([m1,m2,m3])

In [ ]:
n1 = np.mgrid[3:7, 8:11]
n1

In [ ]:
n2 = np.mgrid[7:11, 11:14]
n2

In [ ]:
n3 = np.concatenate([n1, n2])
n3

In [ ]:
n4 = np.concatenate([n1, n2], axis=1)
n4

In [ ]:
o1 = np.arange(1,4)
o2 = np.array([[4,5,6],[7,8,9],[10,11,12]])
o1, o2

In [ ]:
# o3 = np.concatenate([o1,o2])

In [ ]:
# Vertikaler Stapel
o = np.vstack([o1,o2])
o

In [ ]:
# Horizontaler Stapel
np.hstack([o1.reshape((3,1)),o2])

In [ ]:
# weitere Achse mit np.dstack

## 5.5 Zerlegen von Arrays

In [ ]:
o

In [ ]:
np.split(o, [1])

In [ ]:
np.split(o, [1,2])

In [ ]:
np.split(o, [1,3])

In [ ]:
np.split(o, [1,4])

In [ ]:
# vertikales Zerlegen
np.vsplit(o,[2])

In [ ]:
# horizontales Zerlegen
np.hsplit(o,[2])

## 5.6 Vektorisierung (UFunctions)

In [ ]:
# Beispiel zum Einstieg

def testrechnung(zahl):
    return np.sin(np.pi*zahl)

def testfunktion(zahlen):
    l = len(zahlen)
    result = np.empty(l)
    for i in range(l):
        result[i] = testrechnung(zahlen[i])
    return result

In [ ]:
zahlen = np.random.randint(1,100, size=10)
testfunktion(zahlen)

In [ ]:
zahlen = np.random.randint(1,100, size=1000000)
%timeit testfunktion(zahlen)

In [ ]:
schneller = np.vectorize(testrechnung)
def testfunktion2(zahlen):
    return schneller(zahlen)

In [ ]:
zahlen = np.random.randint(1,100, size=1000000)
%timeit testfunktion2(zahlen)

In [ ]:
zahlen = np.random.randint(1,100, size=10)
testfunktion(zahlen), testfunktion2(zahlen)

In [ ]:
# weitere eingebaute Vektorisierungen:
a = np.arange(1,20)
a

In [ ]:
print(a+1)

In [ ]:
print(a*2)

In [ ]:
a = np.mgrid[1:6,4:7]
a

In [ ]:
b = np.mgrid[0:5,2:5]
b

In [ ]:
a*b

In [ ]:
2**a

In [ ]:
a*2-b

In [ ]:
np.exp(a)

In [ ]:
# wenn statt * multiply (analog +, - , //, % ...) verwendet wird, lässt sich die
# Ausgabe vorgeben:

in_data = np.arange(10)
in_data

In [ ]:
out_data = np.zeros(20)
out_data

In [ ]:
np.multiply(in_data, 2, out=out_data[5:15])

In [ ]:
out_data

## 5.7 Reduktion und Akkumulation

In [ ]:
a = np.arange(1,5)
a

In [ ]:
np.multiply.reduce(a)

In [ ]:
np.add.reduce(a)

In [ ]:
a

In [ ]:
np.add.accumulate(a)

In [ ]:
np.multiply.accumulate(a)

In [ ]:
np.multiply.outer(a,a)

In [ ]:
np.add.outer(a,a)

## 5.8 Aggregation

In [ ]:
a = np.arange(1,101)
a

In [ ]:
sum(a)

In [ ]:
np.sum(a)

In [ ]:
testarray = np.random.rand(100000)

In [ ]:
%timeit sum(testarray)

In [ ]:
%timeit np.sum(testarray)

In [ ]:
print(np.min(a), np.min(testarray))

In [ ]:
print(np.max(a), np.max(testarray))

In [ ]:
# Mittelwert
print(np.mean(a), np.mean(testarray))

In [ ]:
# Standardabweichung
print(np.std(a), np.std(testarray))

In [ ]:
# Varianz
print(np.var(a), np.var(testarray))

In [ ]:
# Median
print(np.median(a), np.median(testarray))

In [ ]:
# Index des kleinsten Wertes
print(np.argmin(a), np.argmin(testarray))

In [ ]:
print(a[np.argmin(a)], testarray[np.argmin(testarray)])

In [ ]:
# Index des größten Wertes
print(np.argmax(a), np.argmax(testarray))

In [ ]:
print(a[np.argmax(a)], testarray[np.argmax(testarray)])

## 5.9 Test auf True

In [ ]:
a1 = [False,False,False,False,False,False,False,False,False,False]
np.any(a1)

In [ ]:
a2 = [False,False,False,True,False,False,False,False,False,False]
np.any(a2)

In [ ]:
a3 = [True,False,True,True,True,True,True,True,True]
np.all(a3)

In [ ]:
a3 = [True,True,True,True,True,True,True,True,True]
np.all(a3)

## 5.10 Broadcasting

In [ ]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([2,3,4])

In [ ]:
m1

In [ ]:
m1 + 5

In [ ]:
m2 - 1

In [ ]:
m1 + m2

In [ ]:
m1 * m2

In [ ]:
m1 * m2 * 2

In [ ]:
m3 = np.random.random(10)
m3

In [ ]:
m3.mean()

In [ ]:
m3 = m3 - m3.mean()
m3

In [ ]:
m3.mean()

In [ ]:
m1

In [ ]:
m1 < 3

In [ ]:
m1 >= 4

In [ ]:
m1 < m2

In [ ]:
m2 <= m1

In [ ]:
np.count_nonzero([1,2,0,3,2])

In [ ]:
np.count_nonzero(m1 < m2)

In [ ]:
np.sum(m1 < 3)  # True 1 und False 0

In [ ]:
np.any(m2 > 3)

In [ ]:
np.any(m2 > 4)

In [ ]:
np.all(m1 < 10)

In [ ]:
m1

In [ ]:
np.all(m1 < 4, axis = 0)

In [ ]:
np.all(m1 < 4, axis = 1)

In [ ]:
m1 < 5

## 5.11 Maskierung

In [ ]:
m1[m1 < 5]  

In [ ]:
n1 = np.array([1,1,0,1,0,0,1,0], dtype = bool)
n2 = np.array([1,0,1,0,0,0,1,1], dtype = bool)

In [ ]:
n1, n2

In [ ]:
n1 & n2

In [ ]:
n1 | n2

In [ ]:
n1 ^ n2

## 5.12 Fancy Indexing

In [ ]:
beispiel = np.arange(20)+1
beispiel

In [ ]:
index_liste = [1,2,4,6,10,12,16,18]

In [ ]:
beispiel[index_liste]

In [ ]:
index_liste2 = np.array([[3,4,5],[7,8,9]])
index_liste2

In [ ]:
beispiel[index_liste2]

In [ ]:
beispiel2 = np.mgrid[1:5,5:10]
beispiel2

In [ ]:
index_liste3 = [3,2,1]

In [ ]:
beispiel2[0,index_liste3]

In [ ]:
beispiel2[1,index_liste3]

In [ ]:
beispiel2[0,index_liste3[1:]]

In [ ]:
beispiel2

In [ ]:
beispiel2[0,index_liste3[1:]] = [[1,2,3,4,5],[6,7,8,9,10]]
beispiel2

## 5.13 Sortieren

In [ ]:
a = np.arange(20)
a

In [ ]:
np.random.shuffle(a)
a

In [ ]:
np.sort(a)

In [ ]:
beispiel2

In [ ]:
np.sort(beispiel2)

In [ ]:
np.sort(beispiel2, axis = 0)

In [ ]:
np.sort(beispiel2, axis = 1)

In [ ]:
np.sort(beispiel2, axis = None)

In [ ]:
a

In [ ]:
indices = np.argsort(a)
indices

In [ ]:
a[indices]

In [ ]:
a

In [ ]:
np.partition(a, 5) # Teilfunktion von Quicksort

In [ ]:
np.argpartition(a,5)

In [ ]:
a[np.argpartition(a,5)]