In [30]:
#QUESTION ONE

import numpy as np

"""Beim Reshaping eines Numpy-Arrays ändert man die Form des Arrays, 
ohne dabei dessen Inhalte zu verändern. Das ist zum Beispiel praktisch, 
wenn man ein eindimensionales Array in ein mehrdimensionales Array umwandeln möchte oder umgekehrt.
Hier ist ein Beispiel für ein eindimensionales Array, das in ein 2D-Array umgewandelt wird:"""


a = np.array([1,2,3,4,5,6,7,8])
b = a.reshape(2,4)
print(b)



a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = a.reshape(2,2,3)
print(b)


"""Beim Slicing von Numpy-Arrays wählt man bestimmte Bereiche aus dem Array aus. 
Man kann zum Beispiel nur bestimmte Zeilen oder Spalten eines 2D-Arrays auswählen oder 
einen Teil eines eindimensionalen Arrays auswählen.
Hier ist ein Beispiel für das Auswählen von bestimmten Zeilen und Spalten aus einem 2D-Array:"""


a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a[1:3, 0:2]
print(b)



"""1D"""

a = np.array([1,2,3,4,5,6,7,8,9,10])
b = a[2:6]
print(b)



[[1 2 3 4]
 [5 6 7 8]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[4 5]
 [7 8]]
[3 4 5 6]


In [39]:
#QUESTION 2
""""Fancy indexing" bezieht sich auf die Technik in NumPy, mit der Arrays mit booleschen Masken oder ganzen Index-Arrays indiziert 
werden können, um bestimmte Elemente auszuwählen oder zu manipulieren. Im vorliegenden Code-Beispiel wird ein 1D-Array a mit 100 zufällig 
generierten Ganzzahlen erstellt. 
Dann wird mithilfe der booleschen Maske a<6 eine neue Variable b erstellt, die aus allen Elementen von a besteht, 
die kleiner als 6 sind. Die ausgewählten Elemente werden dann in ein 2D-Array mit 17 Zeilen und 3 Spalten umgeformt.
Am Ende enthält b also eine 2D-Array, in der nur die Elemente aus a enthalten sind, 
die kleiner als 6 sind, wobei die Anordnung der Elemente in b auf der Reihenfolge basiert, 
in der sie in a erschienen sind. Wie b genau aussieht, hängt von den zufälligen Zahlen ab, die in a generiert wurden, 
aber es wird insgesamt 17 Zeilen und 3 Spalten haben."""

import numpy as np

np.random.seed(42)
a=np.random.randint(0,10,100)
b=a[a<6].reshape(17,3)


b

array([[3, 4, 2],
       [4, 3, 2],
       [5, 4, 1],
       [5, 1, 4],
       [0, 5, 0],
       [2, 3, 2],
       [4, 2, 4],
       [1, 3, 1],
       [4, 1, 3],
       [2, 0, 3],
       [1, 3, 1],
       [5, 5, 3],
       [5, 1, 1],
       [3, 4, 1],
       [4, 0, 0],
       [2, 0, 2],
       [2, 0, 4]])

In [2]:
#QUESTION 3

class decode_encode:
    def __init__(self):
        self.the_letters = "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z".split()
        self.the_values = [eval(
            i) for i in "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26".split()]
        self.letter_val_dict = dict(zip(self.the_letters, self.the_values))
        self.decoded_sentence = ""
        self.encoded_sentence = ""
        self.generated_password = ""
        self.result = []

    def question_one(self, password, sentence):
        self.password = list(password.upper())
        self.sentence = list(sentence.upper())
        password_counter = 0
        for letter in self.sentence:
            if not letter.isalpha():
                self.decoded_sentence += letter
                continue
            if password_counter > len(self.password) - 1:
                password_counter = 0
            sentence_value = self.letter_val_dict.get(letter)
            password_value = self.letter_val_dict.get(
                self.password[password_counter])
            total_value = sentence_value + password_value
            if total_value > 26:
                total_value = total_value - 26
            self.decoded_sentence += self.the_letters[total_value - 1]
            password_counter += 1
        return self.decoded_sentence

    def question_two(self, mysterious_text, password):
        self.password = password
        password_counter = 0
        mysterious_text = list(mysterious_text.upper())
        for letter in mysterious_text:
            if not letter.isalpha():
                self.encoded_sentence += letter
                continue
            if password_counter > len(self.password) - 1:
                password_counter = 0
            sentence_value = self.letter_val_dict.get(letter)
            password_value = self.letter_val_dict.get(
                self.password[password_counter])
            total_value = sentence_value - password_value
            if total_value < 0:
                total_value = total_value + 26
            self.encoded_sentence += self.the_letters[total_value - 1]
            password_counter += 1
        return self.encoded_sentence

    def question_three(self, mysterious_text, real_text):
        """

        One way to solve this question is to mathmatically guess whether we hit the needed password or not, by mathmetically finding the
        difference between the cipher and plain text. If the same letter is deduced as the first letter, then it is likely the password.
        This is an issue as the password SONNES will be guessed as SONNE using this logic.
        
        """



        mysterious_text = list(mysterious_text.upper())
        real_text = list(real_text.upper())
        first_letter = None

        for i in range(len(mysterious_text)):
            if not mysterious_text[i].isalpha():
                continue
            real_value = self.letter_val_dict.get(real_text[i])
            mystery_value = self.letter_val_dict.get(mysterious_text[i])
            total_value = mystery_value - real_value

            if total_value < 0:
                total_value += 26

            if (not i == 0) and (first_letter == self.the_letters[total_value - 1]):
                break

            self.generated_password += self.the_letters[total_value - 1]

            if i == 0:
                first_letter = self.the_letters[total_value - 1]

        return self.generated_password


    def generate_combinations(self, prefix, n):
        if n == 0:
            self.result.append(''.join(prefix))

        else:
            for i in range(26):
                prefix.append(chr(i+65))
                self.generate_combinations(prefix, n-1)
                prefix.pop()

    def question_four(self,mysterious_text, part_text):
        self.generate_combinations([],len(part_text))
        for indexer, password in enumerate(self.result):
            pw_list = list(password)
            pw_index = 0
            the_ciphered_text = ""
            for i in range(len(part_text)):

                if not part_text[i].isalpha():
                    the_ciphered_text+= part_text[i]
                    continue

                if pw_index > len(password) - 1:
                    pw_index = 0
                pw_value = self.letter_val_dict.get(pw_list[pw_index])
                text_value = self.letter_val_dict.get(part_text[i])
                total_value = pw_value + text_value
                if total_value > 26:
                    total_value-=26
                
                the_ciphered_text+= self.the_letters[total_value - 1]
                pw_index+=1

            if the_ciphered_text in mysterious_text:
                print("Likely password:", password, "The password's position:", indexer)
            

# decode_encode().question_one("SONNE","DIES IST EIN KLARTEXT")
# print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
# decode_encode().question_two("WXSG NLI SWS DAOFYXMH","SONNE")
# print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
# decode_encode().question_three("WXSG NLI SWS DAOFYXMH","DIES IST EIN KLARTEXT")
# print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
# decode_encode().question_four("WXSG NLI SWS DAOFYXMH","DIES")


Likely password: BPST The password's position: 28203
Likely password: KWTE The password's position: 191130
Likely password: SONN The password's position: 326183
Likely password: UOHO The password's position: 361180
Likely password: WFAF The password's position: 390057
Likely password: ZRJM The password's position: 451138


In [5]:
# Question 3.3, a different answer :)

"""

If the password's length was known, we can generate all the likely passwords starting with AAAAA to ZZZZZ and try each and every one
on the plaintext. If we get the same sentence as the ciphertext then voila you have the password.

"""
plaintext = "DIES IST EIN KLARTEXT"
ciphertext = "WXSG NLI SWS DAOFYXMH"



alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
passwords = [a+b+c+d+e for a in alphabet for b in alphabet for c in alphabet for d in alphabet for e in alphabet]

the_letters = "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z".split()
the_values = [eval(
            i) for i in "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26".split()]
letter_val_dict = dict(zip(the_letters, the_values))
sentence = list(plaintext)




for indexer, password in enumerate(passwords):
    pw_list = list(password)
    pw_length = len(password) - 1
    pw_index = 0
    the_ciphered_text = ""
    for letter in sentence:
        if not letter.isalpha():
            the_ciphered_text += letter
            continue

        password_value = letter_val_dict.get(password[pw_index])
        sentence_value = letter_val_dict.get(letter)
        total_value = sentence_value + password_value
        if total_value > 26:
            total_value-= 26

        the_ciphered_text += the_letters[total_value - 1]

        pw_index+=1

        if pw_index>4:
            pw_index = 0

    if the_ciphered_text == ciphertext:
        print("Password found:", password, "the position of the password was:", indexer)
        break
